FROM ubuntu:20.04
MAINTAINER Dominique Benielli
WORKDIR /
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-setuptools \
        python3-sklearn\
        python3-pytest \
        python3-pytest-cov \
        python3-nose \
        python3-sphinx \
        python3-numpydoc \
        python3-sphinx-gallery \
        python3-matplotlib \
        python3-pil \
        python3-tk \       
        && \
    apt-get clean
RUN apt-get install -y --no-install-recommends locales && \
    apt-get clean && \
    locale-gen en_US.UTF-8 && \
    update-locale en_US.UTF-8 && \
    echo "export LC_ALL=$(locale -a | grep en_US)" >> /root/.bashrc && \
    echo "export LANG=$(locale -a | grep en_US)" >>  /root/.bashrc
COPY requirements.txt .
RUN pip3 install -r requirements.txt
